// Read the metadata svastrino.com already publishes, and keep it.
//   node scripts/captureLegacySeo.mjs
//
// The WordPress site's titles and descriptions were written by hand and have
// been matched to these pages by search engines for years. Regenerating them
// from the article body — which is what this app did — quietly changes the
// wording on 320-odd pages that already rank, and appends a site name that was
// never in the original. So the live wording is fetched once and written to
// legacyRootSeo.js, which the pages read in preference to anything derived.
//
// Re-runnable: the old site can be read until it is switched off, and after
// that the captured file is the only record of what those pages said.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = join(here, '..')
const LIVE = process.env.LEGACY_ORIGIN || 'https://svastrino.com'
const CONCURRENCY = 8

/** Root-level slugs, taken from the sitemap so the list never drifts. */
function rootSlugs() {
  const xml = readFileSync(join(ROOT, 'public', 'sitemap.xml'), 'utf8')
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1].replace(/^https?:\/\/[^/]+/, ''))
    .filter((p) => /^\/[a-z0-9][a-z0-9-]*$/.test(p)) // one segment only
    .map((p) => p.slice(1))
}

const pick = (html, re) => {
  const m = html.match(re)
  return m ? m[1].trim() : ''
}

/** Undo the entity encoding a title arrives in, so it is stored as it reads. */
function decode(s) {
  return s
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;|&#039;/g, "'")
    .replace(/&nbsp;/g, ' ').replace(/&hellip;/g, '…')
    .replace(/&#8217;|&rsquo;/g, '’').replace(/&#8216;|&lsquo;/g, '‘')
    .replace(/&#8220;|&ldquo;/g, '“').replace(/&#8221;|&rdquo;/g, '”')
    .replace(/&#8211;|&ndash;/g, '–').replace(/&#8212;|&mdash;/g, '—')
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function capture(slug, attempt = 1) {
  const url = `${LIVE}/${slug}/`
  try {
    const res = await fetch(url, {
      redirect: 'follow',
      headers: { 'user-agent': 'Mozilla/5.0 (compatible; svastrino-migration)' },
    })
    // The old site rate-limits a burst of requests. Backing off and asking
    // again costs a second and saves a page's wording.
    if ((res.status === 428 || res.status === 429 || res.status >= 500) && attempt <= 3) {
      await sleep(1500 * attempt)
      return capture(slug, attempt + 1)
    }
    if (!res.ok) return { slug, status: res.status }
    const html = (await res.text()).replace(/\n/g, ' ')
    return {
      slug,
      status: 200,
      title: decode(pick(html, /<title>([^<]*)<\/title>/i)),
      description: decode(
        pick(html, /<meta\s+name="description"\s+content="([^"]*)"/i)
        || pick(html, /<meta\s+property="og:description"\s+content="([^"]*)"/i),
      ),
    }
  } catch (err) {
    if (attempt <= 3) { await sleep(1500 * attempt); return capture(slug, attempt + 1) }
    return { slug, status: 0, error: err.message }
  }
}

async function run() {
  const slugs = rootSlugs()
  console.log(`Reading ${slugs.length} pages from ${LIVE} …`)

  const out = []
  let done = 0
  const queue = [...slugs]
  await Promise.all(Array.from({ length: CONCURRENCY }, async () => {
    while (queue.length) {
      const slug = queue.shift()
      out.push(await capture(slug))
      done += 1
      if (done % 50 === 0) process.stdout.write(`  …${done}\n`)
    }
  }))

  const ok = out.filter((r) => r.status === 200 && r.title)
  const missing = out.filter((r) => r.status !== 200 || !r.title)
  ok.sort((a, b) => a.slug.localeCompare(b.slug))

  const esc = (s) => JSON.stringify(s)
  const body = ok.map((r) =>
    `  ${esc(r.slug)}: {\n    title: ${esc(r.title)},\n    description: ${esc(r.description)},\n  },`,
  ).join('\n')

  writeFileSync(join(ROOT, 'src', 'seo', 'legacyRootSeo.js'),
`// Generated by scripts/captureLegacySeo.mjs — do not edit by hand.
//
// What svastrino.com's own pages said, read from the live WordPress site before
// it was replaced. These titles and descriptions were written for these pages
// and search engines have matched them for years, so they are used word for
// word rather than regenerated from the article body.
//
// Keyed by root slug, which is also the address: /law, /creative-writing.
export const LEGACY_ROOT_SEO = {
${body}
}

/** What the old site published for this slug, if anything. */
export function legacyRootSeo(slug) {
  if (!slug) return null
  return LEGACY_ROOT_SEO[String(slug).toLowerCase()] || null
}
`)

  console.log(`\n✓ captured ${ok.length} pages → src/seo/legacyRootSeo.js`)
  console.log(`    with a description: ${ok.filter((r) => r.description).length}`)
  if (missing.length) {
    console.log(`⚠ ${missing.length} could not be read (they keep the wording this app derives):`)
    missing.slice(0, 12).forEach((r) => console.log(`    /${r.slug} — ${r.error || `HTTP ${r.status}`}`))
    if (missing.length > 12) console.log(`    …and ${missing.length - 12} more`)
  }
}

run().catch((err) => { console.error('✗', err.message); process.exit(1) })
